### ISSUE TITLE
Missing Previous Teams CTA 

### ISSUE THREAD

**Issue by haydencordeiro** [flockflair-dbit/acm-website#51]
https://dbit.acm.org/team/2018/
https://dbit.acm.org/team/2017/
https://dbit.acm.org/team/2019/

Requirements:
Please make it dynamic so that this issue doesnt arise again in the future
![image](https://github.com/flockflair-dbit/acm-website/assets/40896224/89b9e731-17c5-49a1-9dea-90f4b04f3603)
![image](https://github.com/flockflair-dbit/acm-website/assets/40896224/9c443bf3-5365-41f6-a742-70a05ea53da5)

**Comment by haydencordeiro** [comment]
@yashaskhot 
FYI @grejojoby

**Comment by haydencordeiro** [comment]
https://github.com/flockflair-dbit/acm-website/pull/53

@grejojoby @yashaskhot 

![image](https://github.com/flockflair-dbit/acm-website/assets/40896224/e62ef02c-73e2-4056-8a47-96e68ccf42a6)
![image](https://github.com/flockflair-dbit/acm-website/assets/40896224/97c4bea5-c7a6-4fb7-a8d7-dd66207e5a88)
![image](https://github.com/flockflair-dbit/acm-website/assets/40896224/c39f84d2-b25d-4dbd-a7c7-64dcf30f247e)

**Comment by grejojoby** [comment]
Should we not show all the other years in the previous teams section when opening for a particular year?
Actually my initial thought was that way when i had made it. 
can rename the section if required.

**Comment by yashaskhot** [comment]
accha so all years should be present below na?

**Comment by haydencordeiro** [comment]
I had thought of the same thing, but then when i seen the code I thought this was what is expected

**Comment by haydencordeiro** [comment]
![image](https://github.com/flockflair-dbit/acm-website/assets/40896224/193cd93e-40c4-4de3-98de-a457b3ced5ac)
![image](https://github.com/flockflair-dbit/acm-website/assets/40896224/415b8ae2-88f7-47eb-8289-061689501e05)

Something like this?

**Comment by yashaskhot** [comment]
ig yes

**Comment by haydencordeiro** [comment]
@grejojoby Should i go ahead and merge this?

**Comment by haydencordeiro** [comment]
Merging this pr and closing this issue
